# Generated by Django 4.2 on 2024-01-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='questions',
        ),
        migrations.AlterField(
            model_name='question_set',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.category'),
        ),
    ]
