# Generated by Django 4.2 on 2024-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.question'),
        ),
    ]
