# Generated by Django 4.2 on 2024-01-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='question_sets',
        ),
        migrations.AddField(
            model_name='question_set',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
